### ISSUE TITLE
tailwindcss 插件注册问题

### ISSUE THREAD

**Issue by sonofmagic** [wws1993/demo#1]
我在我的 gulp 模板里面，安装使用了 @egoist/tailwindcss-icons， 倒是使用很正常 https://github.com/sonofmagic/weapp-tailwindcss/tree/main/demo/gulp-app

然后我 fork 了你这个项目，的确复现了这个问题，一注册 @egoist/tailwindcss-icons ,gulp 就报错了, 怀疑是 gulp task 的问题

**Comment by wws1993** [comment]
> 我在我的 gulp 模板里面，安装使用了 @egoist/tailwindcss-icons， 倒是使用很正常 https://github.com/sonofmagic/weapp-tailwindcss/tree/main/demo/gulp-app
> 
> 然后我 fork 了你这个项目，的确复现了这个问题，一注册 @egoist/tailwindcss-icons ,gulp 就报错了, 怀疑是 gulp task 的问题

现在可以了，我重新拉了一下您的代码。。
